### ISSUE TITLE
app crash: findNavController() fails in onCreate when NavHostFragment is inflated with FragmentContainerView

### ISSUE THREAD

**Issue by RocqJones** [RocqJones/sasaKazi#1]
Error message
```
Caused by: java.lang.IllegalStateException: Activity com.intoverflown.sasakazi.MainActivity@8ffe259 does not have a NavController set on 2131230950
        at androidx.navigation.Navigation.findNavController(Navigation.java:61)
        at androidx.navigation.ActivityKt.findNavController(Activity.kt:30)
        at com.intoverflown.sasakazi.MainActivity.onCreate(MainActivity.kt:18)
        at android.app.Activity.performCreate(Activity.java:8000)
```

**Comment by RocqJones** [comment]
Solution: Replaced ```val navController = findNavController(R.id.nav_host_fragment)``` in MainActivity with the following and it worked
```
val navHostFragment = supportFragmentManager.findFragmentById(R.id.my_nav_host_fragment) as NavHostFragment
val navController = navHostFragment.navController
```
