### ISSUE TITLE
java.lang.NullPointerException on MainActivity

### ISSUE THREAD

**Issue by RocqJones** [RocqJones/sasaKazi#2]
2021-01-27 23:12:59.087 32238-32284/com.intoverflown.sasakazi E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
2021-01-27 23:13:00.837 32238-32238/com.intoverflown.sasakazi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.intoverflown.sasakazi, PID: 32238
    java.lang.NullPointerException
        at com.intoverflown.sasakazi.MainActivity$onStart$1.onDataChange(MainActivity.kt:96)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
        at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:451)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by RocqJones** [comment]
You get navigation header view by: 
```
val navView: NavigationView = findViewById(R.id.nav_view)
val headerView: View = navView.getHeaderView(0)
```
...before initializing Firebase References and then do as follows before setting the text on the nav drawer
```
        navFullName = headerView.findViewById(R.id.nav_fullName)
        navEmailAddress = headerView.findViewById(R.id.nav_emailAddress)
```

**Comment by RocqJones** [comment]
Now you can set a text from Firebase as follows:
```
        val mUser = mAuth!!.currentUser
        val mUserReference = mDatabaseReference!!.child(mUser!!.uid)
        navEmailAddress?.text = mUser.email
```
